Docker build in AWS (Workflow)

diff --git a/.github/workflows/test-ssh.yml b/.github/workflows/test-ssh.yml
--- a/.github/workflows/test-ssh.yml
+++ b/.github/workflows/test-ssh.yml
@@ -1,10 +1,10 @@
-name: Test SSH to AWS
+name: Deploy to AWS
 
 on:
   workflow_dispatch:
 
 jobs:
-  test-ssh:
+  deploy:
     runs-on: ubuntu-latest
 
     steps:
@@ -18,16 +18,21 @@ jobs:
 
           ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
 
-      - name: Test connection
-        run: |
-          ssh \
-            -i ~/.ssh/github_actions_motogp \
-            ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} \
-            "echo 'SSH connection successful' && hostname && docker --version && docker compose version"
-
-      - name: Git pull on AWS
+      # set -e means: If any command in the script fails (returns a non-zero exit code), the entire script will immediately stop executing, and the job will be marked as failed.
+      # This is useful for ensuring that if something goes wrong during the execution of the commands, you don't continue with subsequent steps that might depend on the success of earlier commands.
+      - name: Deploy to AWS
         run: |
             ssh \
               -i ~/.ssh/github_actions_motogp \
               ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} \
-              "cd /home/ubuntu/dev/MotoGP && git pull origin main"
+              "cd /home/ubuntu/dev/MotoGP && \
+               set -e && \
+               echo '=== Git pull ===' && \
+               git fetch origin main && \
+               git reset --hard origin/main && \
+               echo '=== Docker build ===' && \
+               docker compose build && \
+               echo '=== Docker deploy ===' && \
+               docker compose up -d && \
+               echo '=== Containers ===' && \
+               docker compose ps"
